import logo from './logo.svg';
import { Car, Van, Truck } from '@phosphor-icons/react';
import image_1 from './image_1.jpg';
import image_2 from './image_2.jpg';
import image_3 from './image_3.jpg';
import image_4 from './image_4.jpg';

export const assets = {
    logo,
};

export const vehicleIcons = {
    sedan: <Car />,
    suv: <Suv />,
    hatchback: <Hatchback />,
    van: <Van />,
    truck: <Truck />,
    coupe: <Coupe />,
};
export const dummyUsers = [
    {
        id: 'user_1',
        email: 'creator1@example.com',
        name: 'Alex Johnson',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        createdAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
        updatedAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
    },
    {
        id: 'user_2',
        email: 'creator2@example.com',
        name: 'Sophia Lee',
        image: 'https://randomuser.me/api/portraits/women/45.jpg',
        createdAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
        updatedAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
    },
    {
        id: 'user_3',
        email: 'creator3@example.com',
        name: 'David Kim',
        image: 'https://randomuser.me/api/portraits/men/72.jpg',
        createdAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
        updatedAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
    },
];


export const dummyListings = [
  {
    id: 'listing_1',
    ownerId: 'user_1',
    title: '2022 Toyota Camry XSE',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    trim: 'XSE',
    body_type: 'Sedan',
    exterior_color: 'Midnight Black Metallic',
    interior_color: 'Black SofTex',
    horsepower: 203,
    doors: 4,
    fuel_type: 'Petrol',
    cylinders: 4,
    engine_capacity_cc: 2487,
    seating_capacity: 5,
    transmission_type: 'Automatic',
    mileage_km: 18400,
    price_per_day: 65,
    deposit: 300,
    min_rental_days: 1,
    max_rental_days: 30,
    description: 'Well-maintained family sedan with sporty XSE trim. Features Apple CarPlay, Android Auto, heated seats, and a sunroof. Perfect for both city drives and road trips.',
    available: true,
    city: 'Ganemulla',
    license_plate: 'WP-CAV-5021',
    status: 'active',
    featured: true,
    images: [image_1, image_2, image_3, image_4],
    platformAssured: true,
    owner: dummyUsers[0],
    createdAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
    updatedAt: 'Thu Oct 16 2025 12:52:10 GMT+0530 (India Standard Time)',
  },
  {
    id: 'listing_2',
    ownerId: 'user_2',
    title: '2023 BMW 3 Series 330i',
    make: 'BMW',
    model: '3 Series',
    year: 2023,
    trim: '330i M Sport',
    body_type: 'Sedan',
    exterior_color: 'Alpine White',
    interior_color: 'Cognac Vernasca Leather',
    horsepower: 255,
    doors: 4,
    fuel_type: 'Petrol',
    cylinders: 4,
    engine_capacity_cc: 1998,
    seating_capacity: 5,
    transmission_type: 'Automatic',
    mileage_km: 9200,
    price_per_day: 120,
    deposit: 600,
    min_rental_days: 2,
    max_rental_days: 14,
    description: 'Luxury sports sedan with M Sport package. Features adaptive suspension, live cockpit professional display, wireless charging, and premium Harman Kardon sound system.',
    available: true,
    city: 'Thalawathugoda',
    license_plate: 'WP-CCC-0002',
    status: 'active',
    featured: true,
    images: [image_1, image_2, image_3, image_4],
    platformAssured: true,
    owner: dummyUsers[1],
    createdAt: 'Fri Nov 01 2025 09:15:00 GMT+0530 (India Standard Time)',
    updatedAt: 'Fri Nov 01 2025 09:15:00 GMT+0530 (India Standard Time)',
  },
  {
    id: 'listing_3',
    ownerId: 'user_3',
    title: '2021 Ford Explorer XLT',
    make: 'Ford',
    model: 'Explorer',
    year: 2021,
    trim: 'XLT',
    body_type: 'SUV',
    exterior_color: 'Iconic Silver Metallic',
    interior_color: 'Ebony Black Cloth',
    horsepower: 300,
    doors: 4,
    fuel_type: 'Petrol',
    cylinders: 6,
    engine_capacity_cc: 2994,
    seating_capacity: 7,
    transmission_type: 'Automatic',
    mileage_km: 34700,
    price_per_day: 85,
    deposit: 400,
    min_rental_days: 1,
    max_rental_days: 30,
    description: 'Spacious 3-row SUV ideal for families or group travel. Features Ford Co-Pilot360, SYNC 3 infotainment, rear-seat entertainment prep, and ample cargo space.',
    available: true,
    city: 'Negombo',
    license_plate: 'WP-KI-2400',
    status: 'active',
    featured: false,
    images: [image_1, image_2, image_3, image_4],
    platformAssured: false,
    owner: dummyUsers[2],
    createdAt: 'Mon Sep 22 2025 14:30:00 GMT+0530 (India Standard Time)',
    updatedAt: 'Mon Sep 22 2025 14:30:00 GMT+0530 (India Standard Time)',
  },
  {
    id: 'listing_4',
    ownerId: 'user_4',
    title: '2023 Tesla Model 3 Long Range',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    trim: 'Long Range AWD',
    body_type: 'Sedan',
    exterior_color: 'Pearl White Multi-Coat',
    interior_color: 'All Black Premium',
    horsepower: 358,
    doors: 4,
    fuel_type: 'Electric',
    cylinders: 0,
    engine_capacity_cc: 0,
    battery_capacity_kwh: 82,
    range_km: 602,
    seating_capacity: 5,
    transmission_type: 'Single-Speed Automatic',
    mileage_km: 11300,
    price_per_day: 110,
    deposit: 500,
    min_rental_days: 1,
    max_rental_days: 21,
    description: 'Premium electric sedan with over 600km of range. Features Autopilot, 15" touchscreen, over-the-air updates, and access to Tesla Supercharger network. Zero emissions, maximum comfort.',
    available: true,
    city: 'Thimbirigasyaya',
    license_plate: 'WP-CBI-8432',
    status: 'active',
    featured: true,
    images: [image_1, image_2, image_3, image_4],
    platformAssured: true,
    owner: dummyUsers[0],
    createdAt: 'Wed Dec 04 2025 11:00:00 GMT+0530 (India Standard Time)',
    updatedAt: 'Wed Dec 04 2025 11:00:00 GMT+0530 (India Standard Time)',
  },
  {
    id: 'listing_5',
    ownerId: 'user_5',
    title: '2020 Toyota HiAce GL Grandia',
    make: 'Toyota',
    model: 'HiAce',
    year: 2020,
    trim: 'GL Grandia',
    body_type: 'Van',
    exterior_color: 'Super White',
    interior_color: 'Beige Fabric',
    horsepower: 177,
    doors: 4,
    fuel_type: 'Diesel',
    cylinders: 4,
    engine_capacity_cc: 2755,
    seating_capacity: 12,
    transmission_type: 'Manual',
    mileage_km: 58900,
    price_per_day: 95,
    deposit: 450,
    min_rental_days: 1,
    max_rental_days: 30,
    description: 'Reliable 12-seater passenger van, perfect for group tours, airport transfers, and family outings. Features rear air conditioning, captain seats, and large cargo area at the back.',
    available: true,
    city: 'Ragama',
    license_plate: 'WP-PI-4079',
    status: 'active',
    featured: false,
    images: [image_1, image_2, image_3, image_4],
    platformAssured: true,
    owner: dummyUsers[1],
    createdAt: 'Tue Aug 12 2025 08:45:00 GMT+0530 (India Standard Time)',
    updatedAt: 'Tue Aug 12 2025 08:45:00 GMT+0530 (India Standard Time)',
  },
];


